import type { Metadata } from "next";
import UserLogin from "@/components/UserLogin";
import './globals.css';
import Providers from "@/components/Providers";
import { getSession } from "@/api/auth";

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async (props: RootLayoutProps) => {
  const { children } = props

  const session = await getSession()

  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <UserLogin />
          {children}
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout
